<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>CubeCheck</RootNamespace>
    <Version>1.1.1</Version>
    <InformationalVersion>1.1.1</InformationalVersion>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <PublishAot>false</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="everything-list.txt">
      <LogicalName>CubeCheck.everything-list.txt</LogicalName>
    </EmbeddedResource>
    <None Remove="everything-list.txt" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net48'">
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
</Project>
